### ISSUE TITLE
drcsim and ROS Indigo

### ISSUE THREAD

**Issue by osrf-migration** [osrf/drcsim#429]
**Original report ([archived issue](https://osrf-migration.github.io/drcsim-gh-pages/#!/osrf/drcsim/issues/429)) by Stefan Kohlbrecher (Bitbucket: [Stefan_Kohlbrecher](https://bitbucket.org/%7Bdb06b03e-7b31-4483-9018-534df5bd723f%7D/)).**

----------------------------------------
I know the plan so far is to only support hydro (http://gazebosim.org/wiki/DRC/ReleaseSchedule). Given the significantly changed competition schedule (adding 6 months), a switch to newer OS and ROS versions seems desirable for various reasons (of course, there also various good reasons not to switch).
Team ViGIR would be very interested in upgrading to 14.04/ROS Indigo. In fact, drcsim is the last remaining roadblock that prevents us from doing so. Any hints on how to best do so are appreciated (building Gazebo/drcsim in our catkin workspace/building them in a separate workspace etc.).

**Comment by osrf-migration** [comment]
**Original comment by Nate Koenig (Bitbucket: [Nathan Koenig](https://bitbucket.org/%7Bc862cdd9-fcc8-4419-9fc7-e20db14b8fcb%7D/)).**

----------------------------------------
We are working hard on Gazebo 4.0 feature freeze this week. Next week we will tackle all the DRCSim code. Ideally we'll make everything work with 14.04 and Indigo.

**Comment by osrf-migration** [comment]
**Original comment by Steve Peters (Bitbucket: [Steven Peters](https://bitbucket.org/%7B2ccfed09-18b8-4921-8d58-15ef01092802%7D/), GitHub: [scpeters](https://github.com/scpeters)).**

----------------------------------------
We've already merged [pull request #439](https://osrf-migration.github.io/drcsim-gh-pages/#!/osrf/drcsim/pull-requests/439) and [pull request #440](https://osrf-migration.github.io/drcsim-gh-pages/#!/osrf/drcsim/pull-requests/440) to fix compilation errors on Saucy / Trusty, though issue #419 remains open (related to command synchronization).

I'm personally using trusty and indigo on my development machine, so I'll help with this.

**Comment by osrf-migration** [comment]
**Original comment by Steve Peters (Bitbucket: [Steven Peters](https://bitbucket.org/%7B2ccfed09-18b8-4921-8d58-15ef01092802%7D/), GitHub: [scpeters](https://github.com/scpeters)).**

----------------------------------------
Currently the default branch of drcsim does not compile against the default branch of gazebo. I'm working on it.

**Comment by osrf-migration** [comment]
**Original comment by John Hsu (Bitbucket: [hsu](https://bitbucket.org/%7B0a186eae-abf0-4514-a951-23db5eccc286%7D/), GitHub: [hsu](https://github.com/hsu)).**

----------------------------------------
[atlas_v3_simple_shapes branch](https://github.com/osrf/drcsim/blob/846d64849b29ae296bfccb5ae7da22424f86592b/) should compile against gazebo 4.0 candidate (current default branch).

see changesets 846d64849b29ae296bfccb5ae7da22424f86592b, 287a2d20bf5eb6491d62dcbe51701ff4b5577e58, and 6f6e5102eed07ad6525d5889acc203152ba04ed6.

and [gazebo_ros_pkgs branch compatibility_gazebo_4.0](https://github.com/ros-simulation/gazebo_ros_pkgs/tree/compatibility_gazebo_4.0) is needed too for hydro ([pull request 215](https://github.com/ros-simulation/gazebo_ros_pkgs/pull/215)).

**Comment by osrf-migration** [comment]
**Original comment by Nate Koenig (Bitbucket: [Nathan Koenig](https://bitbucket.org/%7Bc862cdd9-fcc8-4419-9fc7-e20db14b8fcb%7D/)).**

----------------------------------------

* changed state from "new" to "resolved"

DRCSim 4.0 is compatible with ROS indigo.
